Implement dynamic plugin loading
acm-uiuc/twilight pull request #11
Opened 2017-03-15 23:29 UTC by wchill

Plugins can now be loaded at runtime. Currently plugins will be cycled through on a fixed rotation; the logic for this can be changed if necessary.

Define the plugin directory in `config.yml`, plugin order, priority and persistence in `plugins.yml`, and plugins can provide their own config files if they need them (which should be loaded using ConfigLoader).

2017-03-15 23:54 UTC, modi95 requested changes
Please add docstrings. And avoid using literals.

2017-03-15 23:54 UTC, modi95 commented on plugin_manager.py
> +                for pixel in tile_matrix:
Add comment about what happens when you write to a tile which doesn't have a twilight unit

2017-03-15 23:54 UTC, modi95 commented on plugin_manager.py
> +    def getNextPlugin(self):
Add docstring

2017-03-15 23:54 UTC, modi95 commented on plugin_manager.py
> +        self.blocked = {}
What is self.blocked?

2017-03-15 23:54 UTC, modi95 commented on plugin_manager.py
> +            if next_module and not next_module == current_module:
Please add a default module and throw an exception.

2017-03-15 23:54 UTC, modi95 commented on plugin_manager.py
> +                time.sleep(0.1)
There's a flag in the config file for safe timeouts. Please do not use literals.

2017-03-15 23:54 UTC, modi95 commented on plugins.yml
> +    persistent: False
What does persistent do @warut-vijit

2017-03-16 00:00 UTC, warut-vijit commented on plugins.yml
> +    persistent: False
"Persistent" indicates whether a particular plugin should be removed from the queue after executing for one cycle or remain on the queue. An example of the latter is an alarm, which should remain on the queue by default

2017-03-16 00:01 UTC, modi95 commented on plugins.yml
> +    persistent: False
Pls that to the plugins.yml header 😄

2017-03-16 00:02 UTC, modi95 commented on plugin_base.py
>      def setTileMatrix(self, tile_matrix):
We're using snek case not camel case.

2017-03-16 00:08 UTC, modi95 commented on plugin_manager.py
> +            while time.time() < current_time + self.config["PLUGIN_CYCLE_LENGTH"]:
I'm a bit confused about what these times are supposed to do.

2017-03-16 00:13 UTC, warut-vijit commented on plugin_manager.py
> +        self.blocked = {}
Fixed, added to comments

2017-03-16 00:14 UTC, warut-vijit commented on plugin_manager.py
> +            while time.time() < current_time + self.config["PLUGIN_CYCLE_LENGTH"]:
changed variable name to be more clear

2017-03-16 00:19 UTC, warut-vijit commented on plugin_base.py
>      def setTileMatrix(self, tile_matrix):
slippery snek cased

2017-03-16 00:39 UTC, modi95 approved these changes

2017-03-16 00:48 UTC, merged