FEATURE #14: Apply filters to light data frames
acm-uiuc/twilight pull request #19
Opened 2017-03-18 23:08 UTC by warut-vijit

Adds filters to the YAML file and creates the Filter class. Also adds sample filter, greyscale

2017-03-20 03:56 UTC, modi95 requested changes

2017-03-20 03:56 UTC, modi95 commented on filter_base.py
> +    def applyToFrame(self, tile_matrix):
snek_case pls ❤️

2017-03-20 03:56 UTC, modi95 commented on filters/greyscale/__init__.py
> +class GreyscaleFilter(Filter):
snek_case here and elsewhere

2017-03-20 03:56 UTC, modi95 commented on plugin_manager.py
> +        """Helper function to retrieve plugin and filter scripts"""
Please describe args and return values. 
See PEP 257 / twilight.py for reference

Fix docstrings similarly elsewhere as well please.

2017-03-20 03:56 UTC, modi95 commented on plugin_manager.py
> +                available_filters[filter_folder] = {
Remove this failsafe and throw an exception instead please.
Ping me if this seems like an odd request 😄

2017-03-20 03:56 UTC, modi95 commented on plugin_manager.py
> +    def load_filter(self, filter_name):
This seems like quite a bit of duplication of code. Please add a TODO to figure out how we can fix this in the future.

2017-03-20 03:56 UTC, modi95 commented on plugins.yml
> +    priority: 0
Please add newline at the end of the file.

2017-03-20 03:58 UTC, wchill requested changes

2017-03-20 03:58 UTC, wchill commented on filters/greyscale/__init__.py
> +filter = GreyscaleFilter
filter is a keyword in Python, we should probably actually change the terminology

2017-03-20 03:58 UTC, wchill commented on filter_base.py
> +        raise NotImplementedError
Filters should also be able to drop frames if necessary (by returning None, perhaps)

2017-03-20 03:58 UTC, wchill commented on plugin_manager.py
> +        """Loads plugin named plugin_name from plugins folder. Returns 0 if successful, else 1"""
Why not just return True/False, this isn't C

2017-03-20 03:58 UTC, wchill commented on plugin_manager.py
> +        """Loads filter named filter_name from filters folder. Returns 0 if successful, else 1"""
Same here

2017-03-20 04:21 UTC, wchill commented on plugin_manager.py
> +        """Loads plugin named plugin_name from plugins folder. Returns 0 if successful, else 1"""
Actually, make it raise an Exception

2017-03-20 18:57 UTC, warut-vijit commented on plugin_manager.py
> +        """Loads plugin named plugin_name from plugins folder. Returns 0 if successful, else 1"""
I'm not sure how you want the program to run, but according to what I understand, the script should continue running even if the plugin fails to load. That is, if one person makes an error in requesting a plugin, it shouldn't cause the entire Twilight system to crash.

2017-03-20 18:57 UTC, warut-vijit commented on plugin_manager.py
> +        """Loads filter named filter_name from filters folder. Returns 0 if successful, else 1"""
See above

2017-03-20 19:50 UTC, modi95 commented
There are a couple of more 🐍 _case issues. Also the line ending at the end of the plugins.yml file.

2017-03-20 19:55 UTC, modi95 commented on plugin_manager.py
> +        """Loads plugin named plugin_name from plugins folder. Returns 0 if successful, else 1"""
Depending on the behavior we want later, we can catch the exception in whatever is running this. It's better convention.

2017-03-20 19:59 UTC, wchill commented on plugin_manager.py
>                  current_plugin = imp.load_source("__init__", next_module["path"]).plugin()
I forgot to mention that `imp.load_source` is deprecated. See #20 for how I solved the deprecation issue.

2017-03-20 19:59 UTC, modi95 commented on filters/greyscale/__init__.py
> +class GreyscaleFilter(Filter):
Marking as done because this comment was on a class name

2017-03-20 20:10 UTC, wchill commented on plugin_manager.py
>                  current_plugin = imp.load_source("__init__", next_module["path"]).plugin()
https://github.com/acm-uiuc/twilight/blob/a9cbf7a0cce9b18518bcf8e0ff2a675bdfaafa01/plugin_manager.py#L94

2017-03-20 20:19 UTC, modi95 approved these changes

2017-03-20 20:31 UTC, wchill approved these changes

2017-03-20 20:31 UTC, wchill commented
Don't merge yet until I've had a chance to test the branch

2017-03-21 00:09 UTC, wchill requested changes
Need to test

2017-03-22 08:11 UTC, wchill approved these changes

2017-03-22 08:11 UTC, wchill commented
As I am stepping down from this project, I will no longer be able to test this PR.

2017-03-25 09:28 UTC, merged